cmake_minimum_required(VERSION 3.10)
project(AlgoService)
include_directories(include)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
add_executable(hello src/hello.cpp)
add_executable(test_productstore src/test_productstore.cpp)
add_executable(test_trie src/test_trie.cpp)
add_executable(test_catalog src/test_catalog.cpp)
add_executable(server src/server.cpp)
if (WIN32)
    target_link_libraries(server ws2_32)
endif()
add_executable(test_queue src/test_queue.cpp)