cmake_minimum_required(VERSION 3.10)
project(AlgoService)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
add_executable(hello src/hello.cpp)
add_executable(test_productstore src/test_productstore.cpp)
add_executable(test_trie src/test_trie.cpp)
add_executable(test_catalog src/test_catalog.cpp)